#!/bin/sh

# Termina o script se ocorrer qualquer erro
set -e

# Define variáveis
BRANCH="main"
REPO="origin"
DATAHORA=$(date +'%Y-%m-%d %H:%M:%S')
COMMIT_MSG="Auto commit em $DATAHORA"

# Verifica se o diretório atual é um repositório Git
if [ ! -d .git ]; then
  echo "Este diretório não é um repositório Git. Saindo do script."
  exit 1
fi

# Adiciona todos os arquivos modificados ao commit
git add .

# Verifica se há arquivos adicionados ao commit
if git diff-index --cached --quiet HEAD --; then
  echo "Nenhum arquivo adicionado ao commit. Saindo do script."
  exit 0
fi

# Realiza o commit com a mensagem contendo a data e hora
if ! git commit -m "$COMMIT_MSG"; then
  echo "Erro ao realizar o commit. Saindo do script."
  exit 1
fi

# Realiza o push forçado para o repositório remoto
if ! git push -f $REPO $BRANCH; then
  echo "Erro ao realizar o push. Saindo do script."
  exit 1
fi

echo "Operações de commit e push concluídas com sucesso."

