#!/bin/sh

# Adiciona todos os arquivos modificados ao commit
git add .

# Verifica se há arquivos adicionados ao commit
if git diff-index --cached --quiet HEAD --; then
  echo "Nenhum arquivo adicionado ao commit. Saindo do script."
  exit 0
fi

# Obtém a data e hora atual
datahora=$(date +'%Y-%m-%d %H:%M:%S')

# Realiza o commit com a mensagem contendo a data e hora
git commit -am "Auto commit em $datahora"

# Verifica se o commit foi realizado com sucesso
if [ $? -ne 0 ]; then
  echo "Erro ao realizar o commit. Saindo do script."
  exit 1
fi

# Realiza o push forçado para o repositório remoto
git push -f

# Verifica se o push foi realizado com sucesso
if [ $? -ne 0 ]; then
  echo "Erro ao realizar o push. Saindo do script."
  exit 1
fi

echo "Operações de commit e push concluídas com sucesso."

